[project]
name = "llama-experiment"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.5.0",
    "numpy>=2.2.5",
    "tensorboard>=2.19.0",
    "torch>=2.6.0",
    "transformers[torch]>=4.51.3",
]
